# Generated by Django 5.0.3 on 2024-03-17 04:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drinks", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Drinks",
            new_name="Drink",
        ),
    ]
